env:
  browser: true
  es2021: true
  node: true
  jasmine: true
  codeceptjs/codeceptjs: true
extends: 
  - airbnb-base
  - plugin:codeceptjs/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-new: 0
  no-console: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  no-prototype-builtins: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - "webpack.*.js"
      - "*.conf.js"
plugins:
  - jasmine
  - codeceptjs
